FROM nginx:1.15-alpine

# 输入参数
ENV VUE_APP_SERVER_URL http://27.0.0.1
ENV VUE_APP_TEST 127.0.0.1

COPY nginx/h5bp/ /etc/nginx/h5bp/
COPY nginx/default-privatization.conf /etc/nginx/conf.d/default.conf
RUN rm -rf /usr/share/nginx/html/*
COPY dist/ /usr/share/nginx/html/
COPY nginx/run.sh /run.sh
ENTRYPOINT ["/run.sh"]
EXPOSE 80
